name: Build Check

on:
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install-build-essential
      run: sudo apt-get install build-essential -y

    - name: checkout
      uses: actions/checkout@v4

    - name: build
      run: make run